<?php
/**
 * Created by PhpStorm.
 * User: niuyafei
 * Date: 2018/5/2
 * Time: 下午10:32
 */
namespace common\models;

use Yii;
use yii\db\ActiveRecord;

class Coins extends ActiveRecord
{
	public static function tableName()
	{
		return 'coins';
	}

	public function rules()
	{
		return parent::rules(); // TODO: Change the autogenerated stub
	}
}